services:
  seeder:
    build: .
    command: node build/script.js
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=${REDIS_URL}
  api1:
    build: .
    container_name: rinha_api_1
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${APP_PORT}
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      seeder:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api2:
    build: .
    container_name: rinha_api_2
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${APP_PORT}
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      seeder:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  nginx:
    image: nginx:1.27-alpine
    container_name: rinha_nginx
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "40MB"

  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: rinha_redis_stack
    ports:
      - "6379:6379"
    restart: unless-stopped
