services:
  seeder:
    build:
      context: .
      dockerfile: Dockerfile.seeder
    depends_on:
      redis-stack:
        condition: service_healthy
    environment:
      - REDIS_URL=${REDIS_URL}
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "300MB"
  api1:
    build: .
    container_name: rinha_api_1
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${APP_PORT}
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      seeder:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api2:
    build: .
    container_name: rinha_api_2
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${APP_PORT}
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      seeder:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  nginx:
    image: nginx:1.27-alpine
    container_name: rinha_nginx
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"

  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: rinha_redis_stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "3.5GB"

volumes:
  redis_data:
